---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Look at new tweets

```{r}
library(tidyverse)
library(lubridate)
library(purrr)
library(twitteR)
source("twitterauth.R")
```


Look at new tweets

```{r}

load("trump_tweets_new_df.Rda")

new_tweets <- trump_tweets_new_df %>%
  select(id, statusSource, text, created) %>%
  extract(statusSource, "source", "Twitter for (.*?)<") %>%
  filter(source %in% c("iPhone", "Android"))
```

```{r}
ggplot(new_tweets, aes(created, source)) + geom_point()
```
```{r}
load("trump_tweets_df.Rda")
old_tweets <- trump_tweets_df %>%
  select(id, statusSource, text, created) %>%
  extract(statusSource, "source", "Twitter for (.*?)<") %>%
  filter(source %in% c("iPhone", "Android"))

tweets <- rbind(new_tweets, old_tweets)
ggplot(tweets, aes(created, source)) + geom_point()
```

There are some missing tweets using the API. 

```{r}
setup_twitter_oauth(twitter_consumer_key,
                    twitter_consumer_secret,
                    twitter_access_token,
                    twitter_access_token_secret)

missing_tweets <- userTimeline("realDonaldTrump", n = 3200, maxID = "797812048805695488")
missing_tweets_df <- tbl_df(map_df(missing_tweets, as.data.frame))

more_missing <- userTimeline("realDonaldTrump", n = 3200, maxID = "764053208394182656")
more_missing_df <- tbl_df(map_df(more_missing, as.data.frame))

missing_tweets_df <- rbind(missing_tweets_df, more_missing_df)

missing_tweets <- missing_tweets_df %>%
  select(id, statusSource, text, created) %>%
  extract(statusSource, "source", "Twitter for (.*?)<") %>%
  filter(source %in% c("iPhone", "Android"))

alltweets <- rbind(trump_tweets_df, missing_tweets) 
alltweets <- alltweets[!duplicated(alltweets$id),]

save(alltweets, file = "alltweets.Rda")
```

```{r}
load("alltweets.Rda")

ggplot(alltweets, aes(created, source)) + geom_jitter()
```

It looks like there were a few weeks where Trump was taking a break from Twitter, and that the Android usage stopped around March

```{r}
alltweets %>% filter(source == "Android") %>% top_n(5, created)
```

The last tweet Trump sent from his Android was a LinkedIn workforce report that was positive news for the first two months of his presidency. 

```{r}

```


```{r}
library(stringr)
library(lubridate)

alltweets2 <- alltweets %>% 
  mutate(quote = ifelse(str_detect(text, '^"'), TRUE, FALSE)) %>% 
  mutate(text = ifelse(str_detect(text, '^"'), "", text)) %>% 
  mutate(picture = ifelse(str_detect(text, "t.co"), TRUE, FALSE)) %>% 
  mutate(text = str_replace_all(text, "https://t.co/[A-Za-z\\d]+|&amp;", "")) %>% 
  mutate(hashtag = ifelse(str_detect(text, "#"), TRUE, FALSE)) %>% 
  mutate(date.time = ymd_hms(created, tz = "EST")) %>% 
  mutate(dow = wday(date.time, label = TRUE)) %>% 
  mutate(tod = hour(with_tz(created, tzone = "EST")))



```

```{r}
ggplot(alltweets2, aes(created, source)) + geom_jitter(aes(color = hashtag))
ggplot(alltweets2, aes(created, source)) + geom_jitter(aes(color = picture)) 
ggplot(alltweets2, aes(created, source)) + geom_jitter(aes(color = (picture | hashtag)))
```

```{r}
alltweets2 %>% group_by(tod, source) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(tod, count)) + geom_line(aes(color = source))

```

```{r}
library(tidytext)

reg <- "([^A-Za-z\\d#@']|'(?![A-Za-z\\d#@]))"
tweet_words <- alltweets2 %>%
  filter(!str_detect(text, '^"')) %>%
  mutate(text = str_replace_all(text, "https://t.co/[A-Za-z\\d]+|&amp;", "")) %>%
  unnest_tokens(word, text, token = "regex", pattern = reg) %>%
  filter(!word %in% stop_words$word,
         str_detect(word, "[a-z]"))

tweet_words


```

